### ISSUE TITLE
Support or explain usage in Windows console

### ISSUE THREAD

**Issue by matthew-a-thomas** [rust-osdev/ansi_rgb#7]
In a Windows console you just get garbage like this:

```
[48;2;159;114;0m [0m
```

Probably need to investigate https://docs.microsoft.com/en-us/windows/console/console-modes

Perhaps this functionality needs to go into another crate (or perhaps someone has already implemented this in another crate)

**Comment by matthew-a-thomas** [comment]
Added short blurb in readme and docs
https://github.com/rust-osdev/ansi_rgb/commit/656595937dee314a43a8c4110b909a51d9e7bd06

**Comment by 64** [comment]
Can you explain why this is in the `rust-osdev` organisation? Not a criticism, I just don’t see how it’s related

**Comment by matthew-a-thomas** [comment]
@64 Sure: https://github.com/phil-opp/blog_os/issues/603

In summary, Phillip's blog_os does terminal output. This adds colors. None of the other ANSI/terminal color crates support `no_std`.

I raised this specific issue about Windows consoles because there's nothing about this crate that is environment specific, except that Windows requires additional configuration. I haven't really done anything more than link to MS documentation because I think it's out of the scope of this crate.

Thanks for asking!

**Comment by 64** [comment]
Oh, cool! I think I half expected this to be some kind of state machine for parsing ANSI escape sequences into color info that you can use in VGA textmode (I have that in my kernel). But this also makes sense. Sorry for hijacking the issue, not entirely sure why I decided to do that. Good luck!

**Comment by phil-opp** [comment]
Maybe `bootimage` can set the appropriate console modes on Windows when running/testing a kernel.

**Comment by matthew-a-thomas** [comment]
I'm going to close this because I think the comment in the readme takes care of it. Let me know if I need to open this back up
